#!/bin/sh

echo Stubbing out files for ${1}
BASENAME="crankshaft${1}"
echo $BASENAME

echo "#ifndef __${BASENAME}doth__" >  include/crankshaft/${1}.h
echo "#define __${BASENAME}doth__" >> include/crankshaft/${1}.h
echo "#include <stdbool.h>"        >> include/crankshaft/${1}.h
echo "#include <stdint.h>"         >> include/crankshaft/${1}.h
echo ""                            >> include/crankshaft/${1}.h
echo "#ifdef __cplusplus"          >> include/crankshaft/${1}.h
echo "extern \"C\" {"              >> include/crankshaft/${1}.h
echo "#endif"                      >> include/crankshaft/${1}.h
echo ""                            >> include/crankshaft/${1}.h
echo ""                            >> include/crankshaft/${1}.h
echo ""                            >> include/crankshaft/${1}.h
echo "#ifdef __cplusplus"          >> include/crankshaft/${1}.h
echo "}"                           >> include/crankshaft/${1}.h
echo "#endif"                      >> include/crankshaft/${1}.h
echo "#endif"                      >> include/crankshaft/${1}.h

echo "#include <stdlib.h>"            >  src/${1}.c
echo "#include <stdio.h>"             >> src/${1}.c
echo "#include <stdint.h>"            >> src/${1}.c
echo "#include <stdbool.h>"           >> src/${1}.c
echo ""                               >> src/${1}.c
echo "#include <crankshaft/alloc.h>"  >> src/${1}.c
echo "#include <crankshaft/logger.h>" >> src/${1}.c
echo ""                               >> src/${1}.c
echo "#include <crankshaft/${1}.h>"   >> src/${1}.c
echo ""                               >> src/${1}.c
echo ""                               >> src/${1}.c
echo ""                               >> src/${1}.c
